everybody_recommend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homes.urls')),
    path('polls/', include('polls.urls')),
    path('', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homes/urls.py
from django.urls import path

from . import views


app_name = 'homes'
urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/recommends/<int:recommend_id>/best', views.set_best_recommend, name='set_best_recommend'),
    path('<int:question_id>/tags/add', views.add_tag, name='add_tag'),
    path('<int:question_id>/tags/<int:tag_id>/delete', views.delete_tag, name='delete_tag'),
    path('post', views.post, name='post'),
    path('comment', views.comment, name='comment'),
    path('good', views.good, name='good'),
    path('bad', views.bad, name='bad'),
]

templates/footer.html
<footer></footer>

templates/header.html
<header class="my-header">
  <div class="inner-layout-size">
    <div style="display: flex;">
      <div class="title">
        <a href="{% url 'homes:index' %}">ミンナのススメ</a>
      </div>
      <nav class="my-nav">
        <ul class="my-ul">
          {% if user.is_authenticated %}
          <p>ようこそ、{{ user.get_username }}さん</p>
          <li class="nav-button button-color-1">
            <a href="{% url 'mypage' user.get_username %}">マイページ</a>
          </li>
          <li class="nav-button button-color-1">
            <a href="{% url 'polls:post' %}">質問投稿</a>
          </li>
          <li class="nav-button button-color-1">
            <a href="{% url 'logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-button button-color-1">
            <a href="{% url 'signup' %}">登録</a>
          </li>
          <li class="nav-button button-color-1">
            <a href="{% url 'login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</header>

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8"/>
    <title>ミンナのススメ</title>
    {#    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>#}
    <link rel="stylesheet" href="{% static 'css/vegas.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/top.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.4/css/uikit.min.css"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!-- css include -->
    {% block css %} {% endblock %}
</head>

<body>
<!-- header -->
{% include 'header.html' %}

<!--nav -->
{% include 'nav.html' %}

<!-- contents -->
<div class="uk-section">
    <div class="uk-container uk-container-medium">
        {# 内容 #} {% block content %} {% endblock %}
    </div>
</div>


<!-- footer -->
{% include 'footer.html' %}

<!-- javascript include -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.4/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.4/js/uikit-icons.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% block js %} {% endblock %}


</body>
</html>