everybody_recommend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homes.urls')),
    path('polls/', include('polls.urls')),
    path('', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homes/urls.py
from django.urls import path

from . import views


app_name = 'homes'
urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/recommends/<int:recommend_id>/best', views.set_best_recommend, name='set_best_recommend'),
    path('<int:question_id>/tags/add', views.add_tag, name='add_tag'),
    path('<int:question_id>/tags/<int:tag_id>/delete', views.delete_tag, name='delete_tag'),
    path('post', views.post, name='post'),
    path('comment', views.comment, name='comment'),
    path('good', views.good, name='good'),
    path('bad', views.bad, name='bad'),
]

homes/models.py
from django.db import models

# Create your models here.

homes/views.py
from django.shortcuts import render
from polls.models import Question


def index(request):
    latest_question_list = Question.objects.order_by('-created_at')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'homes/index.html', context)

templates/homes/index.html
{% extends 'layout.html' %} {% load static %}

<!-- css -->
{% block css %}
{% endblock %}

<!-- javascript -->
{% block js %}
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/vegas.min.js' %}"></script>
    <script>
        /* vegas */
        $("#mainvisual").vegas({
            slides: [
                {src: "{% static 'img/bg.png' %}"},
                {src: "{% static 'img/bg2.jpg' %}"},
                {src: "{% static 'img/bg3.jpg' %}"}
            ],
            delay: 2500,
            timer: false,
            transitionDuration: 1000
        });

        var app = new Vue({
            el: "#app",
            delimiters: ["[[", "]]"],
            data: {
                message: "Hello Vue!"
            }
        });
    </script>
{% endblock %}

<!-- contents -->
{% block content %}
    <div class="inner-layout-size top-image">
        <div id="mainvisual" class="img-size"></div>
        <span class="center-title">☆ミンナのススメ☆</span>
    </div>
    <main class="inner-layout-size column-2">
        <div class="left-column">
            <h2 class="title">質問一覧</h2>
            {% if latest_question_list %}
                {% for question in latest_question_list %}
                    <article class="my-article">
                        <h2><a href="{% url 'polls:detail' question.id %}">{{ question.title }}</a></h2>
                        <p>{{ question.reason }}</p>
                    </article>
                {% endfor %}
            {% else %}
                <p>質問がまだありません</p>
            {% endif %}
        </div>
        <div>
            <div class="right-column">
                <section class="ranking">
                    <h2>話題ランキング</h2>
                    <ul class="my-ul">
                        <li>・群馬の衆議院議員のオススメ</li>
                        <li>・嫌いな人をかわすお勧めの方法</li>
                        <li>・豚野郎にオススメのアニメ</li>
                    </ul>
                </section>
                <section class="ranking fadein">
                    <h2>話題ランキング</h2>
                    <ul class="my-ul">
                        <li>・群馬の衆議院議員のオススメ</li>
                        <li>・嫌いな人をかわすお勧めの方法</li>
                        <li>・豚野郎にオススメのアニメ</li>
                    </ul>
                </section>
                <section class="ranking fadein">
                    <h2>話題ランキング</h2>
                    <ul class="my-ul">
                        <li>・群馬の衆議院議員のオススメ</li>
                        <li>・嫌いな人をかわすお勧めの方法</li>
                        <li>・豚野郎にオススメのアニメ</li>
                    </ul>
                </section>
            </div>
        </div>
    </main>

{% endblock %}