everybody_recommend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homes.urls')),
    path('polls/', include('polls.urls')),
    path('', include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homes/urls.py
from django.urls import path

from . import views


app_name = 'homes'
urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [

    path('users/<str:username>/', views.mypage, name='mypage'),
    path('users/question_edit/<int:question_id>/', views.questionEdit, name='questionEdit'),
    path('users/recommend_edit/<int:recommend_id>/', views.recommendEdit, name='recommendEdit'),
    path('users/edit', views.UserChangeView.as_view(), name='edit_profile'),


    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

polls/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Tag(models.Model):
    """
    タグモデル
    """

    name = models.CharField('タグ名', max_length=200, unique=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    """
    質問モデル
    """

    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name='質問ユーザ')
    title = models.CharField('質問タイトル', max_length=200)
    reason = models.TextField('質問理由')
    tags = models.ManyToManyField(Tag, verbose_name='タグ')

    created_at = models.DateTimeField('作成日', auto_now_add=True)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.title


class Recommend(models.Model):
    """
    おすすめモデル
    """

    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name='おすすめユーザ')
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name='対象質問')
    name = models.CharField('おすすめ名', max_length=200)
    reason = models.TextField('おすすめ理由')
    image = models.ImageField(
        'イメージ', upload_to='images/', blank=True, null=True)
    link = models.URLField('リンク', blank=True, null=True)
    goods = models.ManyToManyField(get_user_model(), verbose_name='good', related_name='goods')
    bads = models.ManyToManyField(get_user_model(), verbose_name='bad', related_name='bads')
    is_best = models.BooleanField('ベストレコメンドフラグ', default=False)

    created_at = models.DateTimeField('作成日', auto_now_add=True)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    """
    コメントモデル
    """

    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, verbose_name='コメントユーザ')
    target_question = models.ForeignKey(
        Question, on_delete=models.CASCADE, verbose_name='対象質問')
    target_recommend = models.ForeignKey(Recommend, on_delete=models.CASCADE, blank=True, null=True,
                                         verbose_name='対象おすすめ')
    reply_to = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='返信先コメント')
    contents = models.TextField('コメント内容')
    good_count = models.IntegerField('グッド数', default=0)
    bad_count = models.IntegerField('バッド数', default=0)

    created_at = models.DateTimeField('作成日', auto_now_add=True)
    updated_at = models.DateTimeField('更新日', auto_now=True)

    def __str__(self):
        return self.contents

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    カスタムユーザモデル
    """

    icon = models.ImageField('アイコン', upload_to='icons/', blank=True, default='icons/default.jpg')
    profile = models.CharField('プロフィール', max_length=200, blank=True, null=True)

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

    fields = UserCreationForm.Meta.fields + ('icon', 'profile')


class CustomUserChangeForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('icon', 'username', 'first_name', 'last_name', 'email', 'profile',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['first_name'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['last_name'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['email'].widget.attrs['class'] = 'uk-input uk-form-width-large'
        self.fields['profile'].widget.attrs.update({'class': 'uk-textarea', 'rows': 8})

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from polls.forms import *
from polls.models import *
from .forms import CustomUserChangeForm
from .forms import CustomUserCreationForm
from .models import User


class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'


def mypage(request, username):
    user = User.objects.get(username=username)
    context = {'myuser': user}
    return render(request, 'users/mypage.html', context)


def questionEdit(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question_form = QuestionForm
    tag_form = TagForm

    if request.method == "POST":
        question_form = QuestionForm(request.POST)

        tag_form = TagForm(request.POST)
        if question_form.is_valid() and tag_form.is_valid():
            question.title = question_form.cleaned_data['title']
            question.reason = question_form.cleaned_data['reason']
            question.save()
            tag_form.save()
            m = "success"
        else:
            m = "failes"

        return redirect('questionEdit', question_id=question_id)

    context = {
        'question': question,
        'question_form': question_form,
        'tag': tag_form,
    }

    return render(request, 'users/question_edit.html', context)



def questionEdit(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question_form = QuestionForm
    tag_form = TagForm

    if request.method == "POST":
        question_form = QuestionForm(request.POST)

        tag_form = TagForm(request.POST)
        if question_form.is_valid() and tag_form.is_valid():
            question.title = question_form.cleaned_data['title']
            question.reason = question_form.cleaned_data['reason']
            question.save()
            tag_form.save()
            m = "success"
        else:
            m = "failes"

        return redirect('questionEdit', question_id=question_id)

    context = {
        'question': question,
        'question_form': question_form,
        'tag': tag_form,
    }

    return render(request, 'users/question_edit.html', context)



def recommendEdit(request, recommend_id):

    recommend = get_object_or_404(Recommend, pk=recommend_id)
    recommend_form = RecommendForm(request.POST or None, request.FILES or None)

    if request.method == 'POST' and recommend_form.is_valid():

        recommend.name = recommend_form.cleaned_data['name']
        recommend.reason = recommend_form.cleaned_data['reason']
        recommend.image = recommend_form.cleaned_data['image']
        recommend.link = recommend_form.cleaned_data['link']
        recommend.save()
        return redirect('recommendEdit', recommend_id=recommend.id)

    context = {
        'recommend': recommend,
        'recommend_form': recommend_form,
    }

    return render(request, 'users/recommend_edit.html', context)


class UserChangeView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = CustomUserChangeForm
    template_name = 'users/edit_profile.html'
    success_url = reverse_lazy('edit_profile')

    def get_object(self, queryset=None):
        return self.request.user

templates/users/edit_profile.html
{% extends 'layout.html' %} {% load static %}

{% block content %}

    <h1 class="uk-heading-divider">プロフィール編集</h1>

    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="uk-margin" uk-form-custom>
            <input type="file" name="icon" accept="image/*" id="id_icon">
            <img src="{{ form.instance.icon.url }}" width="300" height="300" alt=""><br>
        </div>
        <div class="uk-margin preview"></div>
        <div class="uk-margin">
            <label class="uk-form-label" for="form-stacked-text">ユーザー名</label><br>
            {{ form.username }}
            <div class="uk-text-meta">{{ form.username.help_text }}</div>
        </div>
        <div class="uk-margin">
            <label class="uk-form-label" for="form-stacked-text">苗字</label><br>
            {{ form.last_name }}
        </div>
        <div class="uk-margin">
            <label class="uk-form-label" for="form-stacked-text">名前</label><br>
            {{ form.first_name }}
        </div>
        <div class="uk-margin">
            <label class="uk-form-label" for="form-stacked-text">メールアドレス</label><br>
            {{ form.email }}
        </div>
        <div class="uk-margin">
            <label class="uk-form-label" for="form-stacked-text">プロフィール</label><br>
            {{ form.profile }}
        </div>
        <div class="uk-margin">
            <button class="uk-button uk-button-primary" type="submit">保存</button>
        </div>
    </form>

{% endblock %}

{% block js %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/users/login.html
{% extends 'layout.html' %} {% load static %}

<!-- css -->
{% block css %}
{% endblock %}

<!-- js -->
{% block js %}
{% endblock %}


<!-- contents -->
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
    </table>

    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

templates/users/mypage.html
{% extends 'layout.html' %} {% load static %}

<!-- css -->
{% block css %}
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}"/>
{% endblock %}


<!-- js -->
{% block js %}
    <script src="{% static 'js/script.js' %}"></script>
    <!-- <script src="{% static 'users/js/three.js' %}"></script> -->
    {% include './script/mypage.html' %}
{% endblock %}


<!-- contents -->
{% block content %}
    <div class="bg-main">
        <div class="inner-layout-size mypage-height">
            <div id="stage"></div>
        </div>
    </div>

    <div class="uk-flex uk-flex-center uk-grid-small uk-margin" uk-grid>

        <div class="uk-width-1-4 uk-margin">
            <div>
                <div class="uk-card uk-card-default">
                    <div class="uk-card-media-top">
                        <img src="{{ myuser.icon.url }}" alt="">
                    </div>
                    <div class="uk-card-body">
                        {% if myuser.get_full_name %}
                            <p class="uk-text-lead">{{ myuser.get_full_name }}</p>
                        {% endif %}
                        <p class="uk-card-title">@{{ myuser.username }}</p>
                        <p class="uk-text-meta">プロフィール</p>
                        <p>{{ myuser.profile | linebreaksbr }}</p>
                        {% if user == myuser %}
                            <a class="uk-button uk-button-primary" href="{% url 'edit_profile' %}">プロフィール編集</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="uk-width-3-4">

            <h1 class="uk-heading-bullet uk-text-center">投稿した質問</h1>
            {% for question in myuser.question_set.all %}
                <div class="uk-card uk-card-default uk-width-2-3@m uk-align-center">
                    <div class="uk-card-header">
                        <h3 class="uk-card-title uk-margin-remove-bottom">
                            {{ question.title }}　
                            <a href="{% url 'questionEdit' question.id %}">[編集]</a>
                        </h3>
                    </div>
                    <div class="uk-card-body">
                        <p>{{ question.reason }}</p>
                    </div>
                </div>
            {% endfor %}

            <h1 class="uk-heading-bullet uk-text-center">投稿したおすすめ</h1>
            {% for recommend in myuser.recommend_set.all %}
                <div class="uk-card uk-card-default uk-width-2-3@m uk-align-center">
                    <div class="uk-card-header">
                        <h3 class="uk-card-title uk-margin-remove-bottom">
                            {{ recommend.name }}
                            <a href="{% url 'recommendEdit' recommend.id %}">[編集]</a>
                        </h3>
                    </div>
                    <div class="uk-card-body">
                        <p>{{ recommend.reason | linebreaksbr }}</p>
                        {% if recommend.image %}
                            <img src="{{ recommend.image.url }}" width="300" height="300">
                        {% endif %}
                    </div>
                    {% if recommend.link %}
                        <p class="uk-link">{{ recommend.link }}</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/question_edit.html
{% extends 'layout.html' %} {% load static %}

<!-- css -->
{% block css %} {% endblock %}

<!-- js -->
{% block js %}
    <script>
        document.querySelector('#id_title').value = '{{ question.title }}'
        document.querySelector('#id_reason').innerHTML = '{{ question.reason }}'
    </script>
{% endblock %}

<!-- contents -->
{% block content %}
    {{ m }}
    <form method="POST" action="">
        {% csrf_token %}
        {{ question_form.title.label }}
        {{ question_form.title }}
        <br/>
        {{ question_form.reason.label }}
        {{ question_form.reason }}
        <br/>
        {{ tag.name.label }}
        {{ tag.name }}

        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/users/recommend_edit.html
{% extends 'layout.html' %} {% load static %}

<!-- css -->
{% block css %} {% endblock %}

<!-- js -->
{% block js %}
    <script>
        document.querySelector('#id_name').value = '{{ recommend.name }}'
        document.querySelector('#id_reason').innerHTML = '{{ recommend.reason }}'
        document.querySelector('#id_link').innerHTML = '{{ recommend.link }}'

        $('form').on('change', 'input[type="file"]', function (e) {
            let file = e.target.files[0],
                reader = new FileReader(),
                $preview = $(".preview");

            if (file.type.indexOf("image") < 0) {
                return false;
            }
            $('img').remove();

            reader.onload = (function (file) {
                return function (e) {
                    $preview.empty();
                    $preview.append($('<img>').attr({
                        src: e.target.result,
                        width: "150px",
                        class: "preview",
                        title: file.name
                    }));
                };
            })(file);

            reader.readAsDataURL(file);
        });
    </script>
{% endblock %}

<!-- contents -->
{% block content %}
        <div class="uk-modal-header">
            <h2 class="uk-modal-title">おすすめを投稿</h2>
        </div>

        <form
                action=""
                method="POST"
                enctype="multipart/form-data"
        >
            {% csrf_token %}
                <div class="uk-margin">
                    <div class="uk-text-meta">{{ recommend_form.name.label }}</div>
                    <div class="uk-inline">
                        {{ recommend_form.name }}
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-text-meta">{{ recommend_form.reason.label }}</div>
                    <div class="uk-inline">
                        {{ recommend_form.reason }}
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-text-meta">
                        {{ recommend_form.image.label }} (オプション)
                    </div>
                    {% if recommend.image %}
                        <div class="uk-margin preview" width="300" height="300"></div>
                        <img src="{{ recommend.image.url }}" width="150" height="150"/><br>
                    {% endif %}
                    <div class="uk-inline">
                        {{ recommend_form.image }}
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-text-meta">
                        {{ recommend_form.link.label }} (オプション)
                    </div>
                    <div class="uk-inline">
                        <a
                                class="uk-form-icon uk-form-icon-flip"
                                href="#"
                                uk-icon="icon: link"
                        ></a>
                        {{ recommend_form.link }}
                    </div>
                </div>
                <button
                        class="uk-button uk-button-default uk-modal-close"
                        type="button"
                >
                    キャンセル
                </button>
                <button class="uk-button uk-button-primary" type="submit">投稿</button>
        </form>
{% endblock %}

templates/users/signup.html
{% extends 'layout.html' %} {% load static %}

<!-- css -->
{% block css %}
{% endblock %}

<!-- js -->
{% block js %}
{% endblock %}


<!-- contents -->
{% block content %}
<h1>Sign up</h1>
<section class="common-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submit">Sign up</button>
    </form>
</section>
{% endblock %}